spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: root
        password: root
        initialize: true

    sql:
        init:
            mode: always
            schema-locations: classpath:schema.sql
            data-locations: classpath:data.sql

    jpa:
        hibernate:
            ddl-auto: none

    h2:
        console:
            enable: true